pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1795960102.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1795960102.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1795960102.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1795960102.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1795960102.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/2135465983.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/2135465983.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/2135465983.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/2135465983.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/2135465983.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/278540527.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:466)
	at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:360)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:205)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:150)
	at oracle.jdbc.driver.T4CMAREngineNIO.flush(T4CMAREngineNIO.java:803)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:821)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/278540527.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:466)
	at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:360)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:205)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:150)
	at oracle.jdbc.driver.T4CMAREngineNIO.flush(T4CMAREngineNIO.java:803)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:821)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/278540527.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:466)
	at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:360)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:205)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:150)
	at oracle.jdbc.driver.T4CMAREngineNIO.flush(T4CMAREngineNIO.java:803)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:821)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/278540527.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:466)
	at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:360)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:205)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:150)
	at oracle.jdbc.driver.T4CMAREngineNIO.flush(T4CMAREngineNIO.java:803)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:821)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/278540527.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:466)
	at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:360)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:205)
	at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:150)
	at oracle.jdbc.driver.T4CMAREngineNIO.flush(T4CMAREngineNIO.java:803)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:821)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/489404466.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/489404466.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/489404466.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/489404466.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1678854096.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/1954633534.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/1954633534.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/1954633534.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/1954633534.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$42/1954633534.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/902418015.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/902418015.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/902418015.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/902418015.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
pattern_IS_UNDEFINEDjava.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/902418015.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-10 14:09:02,491                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/212490300.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-10 14:09:02,497                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/212490300.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-10 14:09:02,499                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/212490300.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-10 14:09:02,501                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/212490300.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-10 14:09:02,503                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/212490300.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:19)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-11 08:45:48,237                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1287712235.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-11 08:45:48,237                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1287712235.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-11 08:45:48,237                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1287712235.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-11 08:45:48,237                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1287712235.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-11 08:45:48,237                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1287712235.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-12 17:02:10,556                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1436664465.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-12 17:02:10,558                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1436664465.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-12 17:02:10,558                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1436664465.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-12 17:02:10,558                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1436664465.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-12 17:02:10,559                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1436664465.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-12 17:06:43,792                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$4(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/1436664465.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-16 13:20:06,722                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/671422673.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-16 13:20:06,724                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/671422673.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-16 13:20:06,726                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/671422673.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-16 13:20:06,728                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/671422673.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-16 13:20:06,730                     close:53   - [] - connection is closed: {0} - e.OracleConnectionCell 
java.sql.SQLRecoverableException: IO Error: An existing connection was forcibly closed by the remote host
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1992)
	at oracle.jdbc.driver.PhysicalConnection.close(PhysicalConnection.java:2748)
	at vn.vnpay.receiver.connect.oracle.OracleConnectionCell.close(OracleConnectionCell.java:51)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$41/671422673.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:20)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:415)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:1118)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:266)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:198)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:140)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:113)
	at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:97)
	at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:833)
	at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:486)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:621)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C7Ocommoncall.doOLOGOFF(T4C7Ocommoncall.java:73)
	at oracle.jdbc.driver.T4CConnection.logoff(T4CConnection.java:1982)
	... 5 common frames omitted
2023-01-18 14:54:53,572                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$5(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/575593575.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-18 14:54:53,573                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$5(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/575593575.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-18 14:54:53,573                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$5(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/575593575.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-18 14:54:53,573                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$5(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/575593575.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-18 14:54:53,574                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool.lambda$getInstancePool$5(RedisConnectionPool.java:45)
	at vn.vnpay.receiver.connect.redis.RedisConnectionPool$$Lambda$12/575593575.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2023-01-18 14:54:53,600                     start:87   - [] - [Message : can not start connection pool] - [Connection pool : vn.vnpay.receiver.connect.kafka.KafkaConnectionPool@5d05ef57] - [Exception : {}] - e.OracleConnectionPool 
org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serializa-tion.StringDeserializer for configuration value.deserializer: Class org.apache.kafka.common.serializa-tion.StringDeserializer could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:640)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:626)
	at vn.vnpay.receiver.connect.kafka.KafkaConnectionCell.<init>(KafkaConnectionCell.java:41)
	at vn.vnpay.receiver.connect.kafka.KafkaConnectionPool.start(KafkaConnectionPool.java:82)
	at vn.vnpay.receiver.main.MainService.main(MainService.java:29)
2023-01-18 14:54:59,827                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$44/2083187920.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:25)
2023-01-18 14:54:59,828                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$44/2083187920.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:25)
2023-01-18 14:54:59,828                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$44/2083187920.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:25)
2023-01-18 14:54:59,828                     close:45   - [] - connection is closed: {0} - is.RedisConnectionCell 
java.lang.NullPointerException: null
	at vn.vnpay.receiver.connect.redis.RedisConnectionCell.close(RedisConnectionCell.java:43)
	at vn.vnpay.receiver.thread.ShutdownThread$$Lambda$44/2083187920.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vn.vnpay.receiver.thread.ShutdownThread.run(ShutdownThread.java:25)
2023-01-18 14:55:03,782                     start:87   - [] - [Message : can not start connection pool] - [Connection pool : vn.vnpay.receiver.connect.kafka.KafkaConnectionPool@17d238b1] - [Exception : {}] - e.OracleConnectionPool 
org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serializa-tion.StringDeserializer for configuration value.deserializer: Class org.apache.kafka.common.serializa-tion.StringDeserializer could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:640)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:626)
	at vn.vnpay.receiver.connect.kafka.KafkaConnectionCell.<init>(KafkaConnectionCell.java:41)
	at vn.vnpay.receiver.connect.kafka.KafkaConnectionPool.start(KafkaConnectionPool.java:82)
	at vn.vnpay.receiver.main.MainService.main(MainService.java:29)
2023-01-18 15:07:46,035                     start:87   - [] - [Message : can not start connection pool] - [Connection pool : vn.vnpay.receiver.connect.kafka.KafkaConnectionPool@17d238b1] - [Exception : {}] - e.OracleConnectionPool 
org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serializa-tion.StringDeserializer for configuration value.deserializer: Class org.apache.kafka.common.serializa-tion.StringDeserializer could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:640)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:626)
	at vn.vnpay.receiver.connect.kafka.KafkaConnectionCell.<init>(KafkaConnectionCell.java:43)
	at vn.vnpay.receiver.connect.kafka.KafkaConnectionPool.start(KafkaConnectionPool.java:82)
	at vn.vnpay.receiver.main.MainService.main(MainService.java:29)
